### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by flysince1998** [CAPSTONE-2022-2023/Group_25#12]
**Description :** 
  Once a user is authenticated and logged on there will be routed to this page which shows all of the products currently available for customers to bid on with their consecutive description in a truncated view. 

**Acceptance Criteria :** 

- A product page is successfully seen once a user is logged on and  authenticated by the app. 
- A user can view products with a brief summary of their description

**Testing :**
-We will test by seeing whether the user created on sign up page logs in and sees the products on the front page as well as their respective brief descriptions

**Comment by marceljar** [comment]
Perfect!
