### ISSUE TITLE
Login /Sign-up

### ISSUE THREAD

**Issue by flysince1998** [CAPSTONE-2022-2023/Group_25#13]
**Description :**
A new/returning user has to be authenticated first before proceeding to see the products offered and bidding for these products: 

**Acceptance Criteria :**

- A new  user can create an account by providing authentic credentials for future verifications 
- An old user can get authenticated by providing the credentials used once they were signing on.
- An indication that the logging in / signing up process was either a success or failure (In our case seeing the products page is a success)

**Testing :**

- We will create one user and on success  that same user is going to log in to our website

**Comment by marceljar** [comment]
Works perfectly!!!
